# Generated by Django 2.2.5 on 2020-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=6)),
                ('description', models.CharField(max_length=100)),
                ('projected', models.PositiveIntegerField(default=0)),
                ('actual', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
