# Generated by Django 2.2.5 on 2020-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('housing', 'Housing'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
