# Generated by Django 2.2.5 on 2020-04-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('work', 'Work'), ('self-employement', 'Self-employement'), ('other', 'Other')], default='other', max_length=6)),
                ('description', models.CharField(max_length=12)),
                ('completed', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
