# Generated by Django 2.2.5 on 2020-04-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200412_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('school', 'School'), ('work', 'Work'), ('self-improvement', 'Self-improvement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
